<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $invoice->invoice_number ?? '' }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; font-size: 12px; line-height: 1.5; margin: 20px; }
        h1 { font-size: 18px; margin-bottom: 20px; color: #213430; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; font-weight: 600; }
        .amount { font-size: 16px; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <h1>Invoice {{ $invoice->invoice_number ?? '' }}</h1>
    <p><strong>{{ config('app.name') }}</strong></p>
    <p>Generated by Finance User</p>

    <table>
        <tr><th>Applicant</th><td>{{ $registration->full_name ?? '—' }}</td></tr>
        <tr><th>Program</th><td>{{ $registration->program->title ?? '—' }}</td></tr>
        <tr><th>Issue Date</th><td>{{ $invoice->issue_date?->format('M d, Y') ?? '—' }}</td></tr>
        <tr><th>Payment Purpose</th><td>{{ $invoice->payment_purpose }}</td></tr>
        <tr><th>Amount</th><td class="amount">${{ number_format($invoice->amount, 2) }}</td></tr>
        <tr><th>Payment Method</th><td>{{ $invoice->payment_method }}</td></tr>
        <tr><th>Status</th><td>{{ $invoice->status }}</td></tr>
        @if (!empty($invoice->notes))
        <tr><th>Notes</th><td>{{ $invoice->notes }}</td></tr>
        @endif
    </table>

    <div class="footer">
        <p>This is an official invoice. Please retain for your records.</p>
    </div>
</body>
</html>
