@extends('admin.layouts.admin')

@section('title', 'Invoice ' . ($invoice->invoice_number ?? ''))

@section('content')
<main class="flex-1">
    <div class="max-w-2xl mx-auto mt-6 px-5">
        <div class="mb-4">
            <a href="{{ route('admin.program_registrations.show', $registration) }}" class="text-[#9E2469] hover:underline flex items-center gap-1">
                <i class="fas fa-arrow-left"></i> Back to Application
            </a>
        </div>

        <div class="bg-[#F6EAF0] rounded-lg p-6 border border-[#E6D8E1] print:shadow-none">
            <div class="flex justify-between items-start mb-6">
                <div>
                    <h1 class="text-2xl font-semibold text-[#213430]">Invoice {{ $invoice->invoice_number ?? '' }}</h1>
                    <p class="text-sm text-[#6C5F67] mt-1">Generated by Finance User</p>
                </div>
                <div class="flex gap-2 no-print">
                    <button onclick="window.print()" class="px-4 py-2 bg-[#9E2469] text-white rounded-md text-sm font-medium hover:bg-[#B52D75]">
                        <i class="fas fa-print mr-1"></i> Print
                    </button>
                    @if ($invoice->file_path)
                        <a href="{{ route('admin.registration_invoices.download', [$registration, $invoice]) }}" class="px-4 py-2 border border-[#9E2469] text-[#9E2469] rounded-md text-sm font-medium hover:bg-[#9E2469] hover:text-white">
                            <i class="fas fa-download mr-1"></i> Download PDF
                        </a>
                    @endif
                </div>
            </div>

            <div class="bg-white rounded-lg p-6 divide-y divide-[#E5D3E9]">
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Applicant</span>
                    <span class="text-[#213430]">{{ $registration->full_name ?? '—' }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Program</span>
                    <span class="text-[#213430]">{{ $registration->program->title ?? '—' }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Issue Date</span>
                    <span class="text-[#213430]">{{ $invoice->issue_date?->format('M d, Y') ?? '—' }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Payment Purpose</span>
                    <span class="text-[#213430]">{{ $invoice->payment_purpose }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Amount</span>
                    <span class="text-[#213430] text-lg font-semibold">${{ number_format($invoice->amount, 2) }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Payment Method</span>
                    <span class="text-[#213430]">{{ $invoice->payment_method }}</span>
                </div>
                <div class="py-3 flex justify-between">
                    <span class="font-medium text-[#213430]">Status</span>
                    <span class="text-[#213430]">{{ $invoice->status }}</span>
                </div>
                @if (!empty($invoice->notes))
                    <div class="py-3">
                        <span class="font-medium text-[#213430] block">Notes</span>
                        <p class="text-[#213430] mt-1">{{ $invoice->notes }}</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
</main>

<style>
    @media print {
        .no-print { display: none !important; }
    }
</style>
@endsection
